version: "2"

run:
  tests: true
  build-tags:
    - bench
    - "!bench"

linters:
  default: none
  enable:
    - asciicheck
    - depguard
    - dogsled
    - dupl
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - copyloopvar
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - tagliatelle
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace

  settings:
    depguard:
      rules:
        Main:
          files:
            - $all
            - "!$test"
          allow:
            - $gostd
        Test:
          files:
            - $test
          allow:
            - $gostd
            - github.com/stretchr/testify